---
defaults: &defaults
  docker:
    - image: canonicalwebteam/dev

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn run build
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  lint:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn run lint
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn run test --max-workers=2
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
